[tool.poetry]
name = "lit-gpt"
version = "0.1.0"
description = ""
authors = ["Lightning AI"]
readme = "README.md"
packages = [{include = "lit_gpt"}]

[[tool.poetry.source]]
name = "pytorch_nightly_cpu"
url = "https://download.pytorch.org/whl/nightly/cpu"
priority = "explicit"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
torch = {version = "^2.1.0dev", source = "pytorch_nightly_cpu"}
pydantic = "1.10.11"
bitsandbytes = "^0.39.1"
scipy = "^1.11.1"
datasets = "^2.13.1"
zstandard = "^0.21.0"
jsonargparse = {extras = ["signatures"], version = "^4.22.1"}
tokenizers = "^0.13.3"
huggingface-hub = "^0.16.4"
lightning = {git = "https://github.com/Lightning-AI/lightning.git", branch= "master"}

[tool.poetry.group.dev.dependencies]
notebook = "^6.5.4"
mypy = "^1.4.1"
isort = "^5.12.0"
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
